/**
 * Known keys resolved in each layer of the system.
 *
 * FRONTEND_RESOLVER_KEYS: Keys explicitly handled by resolveProposalVariables.ts
 * (switch-case + deepGet fallback).
 *
 * BACKEND_FLATTEN_KEYS: Keys produced by domain resolvers in
 * supabase/functions/_shared/resolvers/ (resolveAllVariables).
 *
 * Updated 2026-03-29 after comprehensive audit of all 6 BE resolvers
 * and the FE resolver. Includes dynamic keys (monthly series, annual series,
 * indexed equipment, UC-indexed) and passthrough groups.
 */
export const FRONTEND_RESOLVER_KEYS = new Set<string>([
  "alerta.estimado.texto_pdf", "aneel.last_sync_at", "aneel.run_id", "aneel.snapshot_hash_curto",
  "calculo.consumo_compensavel_kwh", "calculo.consumo_mensal_kwh", "calculo.custo_disponibilidade_kwh",
  "calculo.economia_mensal_rs", "calculo.energia_compensada_kwh", "calculo.geracao_mensal_kwh",
  "calculo.valor_credito_kwh", "cliente.bairro", "cliente.celular", "cliente.cep", "cliente.cidade",
  "cliente.cnpj_cpf", "cliente.email", "cliente.empresa", "cliente.endereco", "cliente.estado",
  "cliente.nome", "comercial.consultor_codigo", "comercial.consultor_email", "comercial.consultor_nome",
  "comercial.consultor_telefone", "comercial.data_hoje", "comercial.descricao", "comercial.empresa_nome",
  "comercial.empresa_nome_fantasia", "comercial.empresa_razao_social", "comercial.projeto_bairro",
  "comercial.projeto_cep", "comercial.projeto_cidade", "comercial.projeto_codigo",
  "comercial.projeto_endereco", "comercial.projeto_estado", "comercial.proposta_codigo",
  "comercial.proposta_identificador", "comercial.proposta_link", "comercial.proposta_link_interativo",
  "comercial.proposta_titulo", "comercial.representante_celular", "comercial.representante_email",
  "comercial.representante_nome", "comercial.responsavel_celular", "comercial.responsavel_email",
  "comercial.responsavel_nome", "comercial.titulo", "conta_energia.co2_evitado_ano",
  "conta_energia.economia_percentual", "conta_energia.gasto_atual_mensal", "customizada.capo_m",
  "customizada.capo_seguro", "customizada.data_hoje", "customizada.descricao", "customizada.investimento",
  "customizada.potencia", "customizada.projeto_bairro", "customizada.projeto_cep",
  "customizada.projeto_cidade", "customizada.projeto_endereco", "customizada.projeto_estado",
  "customizada.servico_garantia", "customizada.titulo", "customizada.vc_a_vista", "customizada.vc_aumento",
  "customizada.vc_calculo_seguro", "customizada.vc_financeira_nome", "customizada.vc_nome",
  "entrada.area_util", "entrada.cidade", "entrada.consumo_mensal", "entrada.custo_disponibilidade_kwh",
  "entrada.dis_energia", "entrada.estado", "entrada.fase", "entrada.tarifa_distribuidora",
  "entrada.tensao_rede", "entrada.tipo_sistema", "entrada.tipo_telhado", "financeiro.capo_m",
  "financeiro.capo_seguro", "financeiro.comissao_total", "financeiro.consultor_comissao",
  "financeiro.custo_instalacao_total", "financeiro.custo_kit", "financeiro.desconto_percentual",
  "financeiro.desconto_valor", "financeiro.economia_25_anos", "financeiro.economia_anual",
  "financeiro.economia_anual_numero", "financeiro.economia_mensal", "financeiro.economia_mensal_numero",
  "financeiro.f_ativo_entrada", "financeiro.f_ativo_nome", "financeiro.f_ativo_parcela",
  "financeiro.f_ativo_prazo", "financeiro.f_ativo_taxa", "financeiro.f_ativo_valor",
  "financeiro.inversor_custo_total", "financeiro.inversor_custo_un", "financeiro.inversor_preco_total",
  "financeiro.inversor_preco_un", "financeiro.investimento", "financeiro.margem_percentual",
  "financeiro.margem_real", "financeiro.margem_valor", "financeiro.modulo_custo_total",
  "financeiro.modulo_custo_un", "financeiro.modulo_preco_total", "financeiro.modulo_preco_un",
  "financeiro.payback_anos", "financeiro.payback_meses", "financeiro.percentual_comissao",
  "financeiro.preco", "financeiro.preco_final", "financeiro.preco_kwp", "financeiro.preco_total",
  "financeiro.preco_watt", "financeiro.preco_watt_numero", "financeiro.valor_comissao",
  "financeiro.valor_instalacao", "financeiro.valor_instalacao_numero", "financeiro.valor_kit",
  "financeiro.valor_kit_numero", "financeiro.valor_outros_custos", "financeiro.valor_servicos",
  "financeiro.valor_total", "financeiro.valor_total_numero", "financeiro.vc_aumento",
  "financeiro.vc_calculo_seguro", "gd.ano_aplicado", "gd.fio_b_percent_cobrado",
  "gd.fio_b_percent_compensado", "gd.regra", "sistema_solar.area_necessaria", "sistema_solar.area_util",
  "sistema_solar.geracao_anual", "sistema_solar.geracao_mensal", "sistema_solar.geracao_mensal_numero",
  "sistema_solar.inversor_fabricante", "sistema_solar.inversor_fabricante_1",
  "sistema_solar.inversor_garantia", "sistema_solar.inversor_modelo",
  "sistema_solar.inversor_potencia_nominal", "sistema_solar.inversor_potencia_nominal_numero",
  "sistema_solar.inversor_quantidade", "sistema_solar.modulo_area", "sistema_solar.modulo_area_numero",
  "sistema_solar.modulo_comprimento", "sistema_solar.modulo_comprimento_numero",
  "sistema_solar.modulo_fabricante", "sistema_solar.modulo_garantia", "sistema_solar.modulo_largura",
  "sistema_solar.modulo_largura_numero", "sistema_solar.modulo_modelo", "sistema_solar.modulo_potencia",
  "sistema_solar.modulo_potencia_numero", "sistema_solar.modulo_quantidade", "sistema_solar.numero_modulos",
  "sistema_solar.potencia", "sistema_solar.potencia_sistema", "sistema_solar.potencia_sistema_numero",
  "sistema_solar.servico_garantia", "tarifa.fio_b_real_kwh", "tarifa.fio_b_usado_kwh", "tarifa.origem",
  "tarifa.precisao", "tarifa.precisao_motivo", "tarifa.te_kwh", "tarifa.tusd_total_kwh",
  "tarifa.vigencia_fim", "tarifa.vigencia_inicio",
]);

// ── Backend resolvers: keys set via domain resolvers ──
// Updated 2026-03-29 — comprehensive extraction from all 6 resolvers.
export const BACKEND_FLATTEN_KEYS = new Set<string>([
  "area_necessaria", "area_util", "bateria_capacidade", "bateria_comprimento",
  "bateria_corrente_maxima_carga", "bateria_corrente_maxima_descarga", "bateria_corrente_recomendada",
  "bateria_custo_total", "bateria_energia", "bateria_fabricante", "bateria_largura", "bateria_modelo",
  "bateria_potencia_maxima_saida", "bateria_preco_total", "bateria_profundidade", "bateria_quantidade",
  "bateria_tensao_carga", "bateria_tensao_nominal", "bateria_tensao_operacao", "bateria_tipo",
  "baterias_custo_total", "baterias_preco_total", "cape_telhado", "capo_i", "capo_m", "capo_seguro",
  "cidade", "cidade_estado", "cliente_bairro", "cliente_celular", "cliente_cep", "cliente_cidade",
  "cliente_cnpj_cpf", "cliente_codigo", "cliente_complemento", "cliente_cpf_cnpj", "cliente_data_nascimento",
  "cliente_email", "cliente_empresa", "cliente_endereco", "cliente_estado", "cliente_estado_civil",
  "cliente_nacionalidade", "cliente_nome", "cliente_numero", "cliente_observacoes", "cliente_profissao",
  "cliente_rg", "cliente_rua", "cliente_telefone", "cliente_tipo_pessoa", "co2_evitado_ano",
  "comissao_rep_p", "comissao_res_p", "concessionaria_aliquota_icms",
  "concessionaria_custo_disponibilidade_bifasico", "concessionaria_custo_disponibilidade_monofasico",
  "concessionaria_custo_disponibilidade_trifasico", "concessionaria_estado", "concessionaria_fio_b_gd",
  "concessionaria_icms", "concessionaria_id", "concessionaria_possui_isencao_scee", "concessionaria_sigla",
  "concessionaria_tarifa_fio_b", "consultor_codigo", "consultor_comissao", "consultor_email",
  "consultor_nome", "consultor_telefone", "consumo_mensal", "consumo_mensal_fp", "consumo_mensal_fp_uc1",
  "consumo_mensal_p", "consumo_mensal_p_uc1", "consumo_mensal_uc1", "creditos_gerados",
  "custo_disponibilidade_kwh", "custo_disponibilidade_kwh_uc1", "data_hoje", "data_hoje_extenso",
  "demanda_adicional", "demanda_contratada", "demanda_contratada_uc1", "demanda_g_preco_uc1",
  "demanda_g_uc1", "demanda_preco", "demanda_preco_uc1", "desconto_percentual", "desconto_valor",
  "descricao", "desvio_azimutal", "dis_energia", "distancia", "dod", "economia_anual_numero",
  "economia_mensal", "economia_mensal_numero", "economia_mensal_percent", "economia_percentual",
  "empresa_bairro", "empresa_cep", "empresa_cidade", "empresa_cnpj", "empresa_cnpj_cpf",
  "empresa_complemento", "empresa_documento", "empresa_email", "empresa_endereco", "empresa_estado",
  "empresa_ie", "empresa_inscricao_estadual", "empresa_inscricao_municipal", "empresa_logo_url",
  "empresa_nome", "empresa_nome_fantasia", "empresa_numero", "empresa_razao_social",
  "empresa_representante_cargo", "empresa_representante_cpf", "empresa_representante_legal",
  "empresa_telefone", "estado", "estrutura", "estrutura_tipo", "f_ativo_carencia", "f_ativo_entrada",
  "f_ativo_entrada_p", "f_ativo_nome", "f_ativo_parcela", "f_ativo_prazo", "f_ativo_taxa", "f_ativo_valor",
  "f_ativo_valor_p", "fase", "fase_uc1", "fator_geracao", "fator_simultaneidade", "geracao_anual",
  "geracao_anual_0", "geracao_anual_numero", "geracao_mensal", "geracao_mensal_numero", "grupo_tarifario",
  "imposto_energia", "imposto_energia_uc1", "inclinacao", "inversor_codigo", "inversor_corrente_saida",
  "inversor_fabricante", "inversor_fabricante_1", "inversor_garantia", "inversor_modelo",
  "inversor_mppts_utilizados", "inversor_potencia_nominal", "inversor_potencia_nominal_numero",
  "inversor_quantidade", "inversor_tensao", "inversor_tipo", "inversores_potencia_maxima_total",
  "inversores_utilizados", "investimento", "kit_codigo", "kit_fechado_custo_total",
  "kit_fechado_preco_total", "kit_fechado_quantidade", "kit_garantia_servico", "margem_percentual",
  "margem_real", "modulo_area", "modulo_area_numero", "modulo_celulas", "modulo_codigo",
  "modulo_coef_temp_isc", "modulo_coef_temp_pmax", "modulo_coef_temp_voc", "modulo_comprimento",
  "modulo_comprimento_numero", "modulo_eficiencia", "modulo_fabricante", "modulo_garantia",
  "modulo_garantia_performance", "modulo_imp", "modulo_isc", "modulo_largura", "modulo_largura_numero",
  "modulo_modelo", "modulo_potencia", "modulo_potencia_numero", "modulo_profundidade",
  "modulo_profundidade_numero", "modulo_quantidade", "modulo_tensao_maxima", "modulo_tipo_celula",
  "modulo_vmp", "modulo_voc", "nome_uc1", "num_ucs", "numero_modulos", "outros_encargos_atual",
  "outros_encargos_atual_uc1", "outros_encargos_novo", "outros_encargos_novo_uc1",
  "p_armazenamento_necessario", "payback", "payback_anos", "payback_meses", "percentual_comissao",
  "peso_total", "potencia", "potencia_ideal_total", "potencia_kwp", "potencia_sistema",
  "potencia_sistema_numero", "poupanca_25", "poupanca_25_anos", "preco", "preco_final", "preco_kwp",
  "preco_por_extenso", "preco_total", "preco_watt", "preco_watt_numero", "projeto_area_util",
  "projeto_bairro", "projeto_bairro_instalacao", "projeto_cep", "projeto_cep_instalacao", "projeto_cidade",
  "projeto_cidade_instalacao", "projeto_codigo", "projeto_complemento_instalacao", "projeto_data_instalacao",
  "projeto_data_previsao_instalacao", "projeto_data_venda", "projeto_endereco", "projeto_estado",
  "projeto_estado_instalacao", "projeto_forma_pagamento", "projeto_geracao_mensal", "projeto_id_externo",
  "projeto_numero", "projeto_numero_instalacao", "projeto_numero_parcelas", "projeto_observacoes",
  "projeto_rua_instalacao", "projeto_status", "projeto_tipo_instalacao", "projeto_uf_instalacao",
  "projeto_valor_entrada", "projeto_valor_equipamentos", "projeto_valor_financiado",
  "projeto_valor_mao_obra", "projeto_valor_parcela", "proposta_aceita_at", "proposta_aceito_em",
  "proposta_codigo", "proposta_data", "proposta_data_envio", "proposta_enviada_at", "proposta_enviado_em",
  "proposta_identificador", "proposta_inflacao_energetica", "proposta_link", "proposta_link_interativo",
  "proposta_motivo_rejeicao", "proposta_num", "proposta_observacoes", "proposta_output_docx_path",
  "proposta_output_pdf_path", "proposta_perda_eficiencia_anual", "proposta_recusa_motivo",
  "proposta_recusada_at", "proposta_rejeitado_em", "proposta_sobredimensionamento", "proposta_status",
  "proposta_titulo", "proposta_validade", "proposta_valido_ate", "proposta_versao", "proposta_versao_atual",
  "proposta_versao_status", "proposta_viewed_at", "qtd_ucs", "rateio_creditos", "rateio_creditos_uc1",
  "rateio_sugerido_creditos", "rateio_sugerido_creditos_uc1", "regra_comp_uc1", "renda_25",
  "renda_fixa_25_anos", "representante_celular", "representante_email", "representante_nome",
  "responsavel_celular", "responsavel_email", "responsavel_nome", "roi_anual", "segmentos_utilizados",
  "servico_garantia", "simulacao_co2_evitado_kg", "simulacao_tipo_conta", "solar_25", "solar_25_anos",
  "subgrupo", "subgrupo_uc1", "t_e_comp_bt_1_uc1", "t_e_comp_bt_2_uc1", "t_e_comp_fp_1_uc1",
  "t_e_comp_fp_2_uc1", "t_e_comp_p_1_uc1", "t_e_comp_p_2_uc1", "tarifa_distribuidora",
  "tarifa_distribuidora_uc1", "tarifa_te_fp", "tarifa_te_fp_uc1", "tarifa_te_p", "tarifa_te_p_uc1",
  "tarifa_tusd_fp", "tarifa_tusd_fp_uc1", "tarifa_tusd_p", "tarifa_tusd_p_uc1", "taxa_desempenho", "tensao",
  "tensao_rede", "tipo", "tipo_sistema", "tipo_telhado", "tipo_uc1", "tir", "titulo", "topologia",
  "transformador_nome", "transformador_potencia", "transformadores_custo_total",
  "transformadores_preco_total", "valor_instalacao_numero", "valor_kit_numero", "valor_por_extenso",
  "valor_total", "valor_total_numero", "vc_a_vista", "vc_aumento", "vc_calculo_seguro",
  "vc_cartao_credito_parcela_1", "vc_cartao_credito_parcela_2", "vc_cartao_credito_parcela_3",
  "vc_cartao_credito_parcela_4", "vc_financeira_nome", "vc_modulo_potencia", "vc_nome", "vc_observacao",
  "vc_parcela_1", "vc_parcela_2", "vc_parcela_3", "vc_total_modulo", "vpl",
]);

export const BACKEND_TEMPLATE_PREVIEW_KEYS = new Set<string>([
  ...BACKEND_FLATTEN_KEYS,
]);

/**
 * Maps canonical dotted keys to their data source path in the snapshot/context.
 */
export const SOURCE_MAP: Record<string, { source: string; path: string }> = {
  "cliente.nome": { source: "cliente", path: "cliente.nome" },
  "cliente.empresa": { source: "cliente", path: "cliente.empresa" },
  "cliente.cnpj_cpf": { source: "cliente", path: "cliente.cpf_cnpj" },
  "cliente.email": { source: "cliente", path: "cliente.email" },
  "cliente.celular": { source: "cliente", path: "cliente.telefone" },
  "cliente.endereco": { source: "cliente", path: "cliente.rua" },
  "cliente.cidade": { source: "cliente", path: "cliente.cidade" },
  "cliente.estado": { source: "cliente", path: "cliente.estado" },
  "cliente.bairro": { source: "cliente", path: "cliente.bairro" },
  "cliente.cep": { source: "cliente", path: "cliente.cep" },
  "entrada.consumo_mensal": { source: "ucs/tecnico", path: "ucs[0].consumo_mensal / tecnico.consumo_total_kwh" },
  "entrada.dis_energia": { source: "ucs/snapshot", path: "snapshot.concessionaria_nome / ucs[0].distribuidora" },
  "entrada.tarifa_distribuidora": { source: "ucs/snapshot", path: "snapshot.tarifa_distribuidora / ucs[0].tarifa_kwh" },
  "sistema_solar.potencia_sistema": { source: "versao/tecnico", path: "versao.potencia_kwp / tecnico.potencia_kwp" },
  "sistema_solar.geracao_mensal": { source: "projeto/tecnico", path: "projeto.geracao_mensal_media_kwh / tecnico.geracao_estimada_kwh" },
  "financeiro.preco_total": { source: "versao/financeiro", path: "versao.valor_total / financeiro.valor_total" },
  "financeiro.economia_mensal": { source: "versao/financeiro", path: "versao.economia_mensal / financeiro.economia_mensal" },
  "financeiro.payback_anos": { source: "versao/financeiro", path: "versao.payback_meses/12 / financeiro.payback_meses/12" },
  "comercial.responsavel_nome": { source: "consultor", path: "consultor.nome" },
  "comercial.empresa_nome": { source: "tenant", path: "tenants.nome" },
  "customizada.vc_financeira_nome": { source: "pagamento_opcoes", path: "pagamento_opcoes[tipo=financ].nome" },
  "customizada.vc_nome": { source: "cliente", path: "cliente.nome (alias legado)" },
};
