/**
 * Known keys resolved in each layer of the system.
 * Generated by static analysis of:
 * - src/lib/resolveProposalVariables.ts (frontend resolver)
 * - supabase/functions/_shared/flattenSnapshot.ts (backend flatten)
 *
 * Keys are stored as dotted canonical keys (without {{ }})
 */

// ── Frontend resolver: keys explicitly handled in resolveFromContext() ──
export const FRONTEND_RESOLVER_KEYS = new Set<string>([
  // Tarifa
  "tarifa.te_kwh", "tarifa.tusd_total_kwh", "tarifa.fio_b_real_kwh",
  "tarifa.fio_b_usado_kwh", "tarifa.precisao", "tarifa.precisao_motivo",
  "tarifa.origem", "tarifa.vigencia_inicio", "tarifa.vigencia_fim",
  // ANEEL
  "aneel.last_sync_at", "aneel.run_id", "aneel.snapshot_hash_curto",
  // GD
  "gd.regra", "gd.ano_aplicado", "gd.fio_b_percent_cobrado", "gd.fio_b_percent_compensado",
  // Cálculo
  "calculo.consumo_mensal_kwh", "calculo.custo_disponibilidade_kwh",
  "calculo.consumo_compensavel_kwh", "calculo.geracao_mensal_kwh",
  "calculo.energia_compensada_kwh", "calculo.valor_credito_kwh",
  "calculo.economia_mensal_rs", "alerta.estimado.texto_pdf",
  // Cliente
  "cliente.nome", "cliente.empresa", "cliente.cnpj_cpf", "cliente.email",
  "cliente.celular", "cliente.endereco", "cliente.cidade", "cliente.estado",
  "cliente.bairro", "cliente.cep",
  // Comercial
  "comercial.responsavel_nome", "comercial.empresa_nome",
  // Entrada
  "entrada.consumo_mensal", "entrada.dis_energia", "entrada.estado",
  "entrada.cidade", "entrada.fase", "entrada.tipo_telhado",
  "entrada.tarifa_distribuidora", "entrada.custo_disponibilidade_kwh",
  "entrada.tensao_rede", "entrada.tipo_sistema",
  // Sistema Solar
  "sistema_solar.potencia_sistema", "sistema_solar.geracao_mensal",
  "sistema_solar.numero_modulos", "sistema_solar.modulo_fabricante",
  "sistema_solar.modulo_modelo", "sistema_solar.modulo_potencia",
  "sistema_solar.modulo_quantidade", "sistema_solar.inversor_fabricante",
  "sistema_solar.inversor_fabricante_1", "sistema_solar.inversor_modelo",
  "sistema_solar.inversor_potencia_nominal", "sistema_solar.inversor_quantidade",
  // Financeiro
  "financeiro.preco_total", "financeiro.preco", "financeiro.preco_final",
  "financeiro.valor_total", "financeiro.economia_mensal", "financeiro.economia_anual",
  "financeiro.economia_25_anos", "financeiro.payback_anos", "financeiro.payback_meses",
  "financeiro.preco_kwp", "financeiro.preco_watt",
  "financeiro.modulo_custo_un", "financeiro.modulo_preco_un",
  "financeiro.modulo_custo_total", "financeiro.modulo_preco_total",
  "financeiro.inversor_custo_un", "financeiro.inversor_preco_un",
  "financeiro.inversor_custo_total", "financeiro.inversor_preco_total",
  // Financeiro indexed (f_*)
  "financeiro.f_nome_1", "financeiro.f_parcela_1", "financeiro.f_taxa_1",
  "financeiro.f_prazo_1", "financeiro.f_entrada_1", "financeiro.f_valor_1",
  // Financeiro ativo
  "financeiro.f_ativo_nome", "financeiro.f_ativo_parcela",
  "financeiro.f_ativo_taxa", "financeiro.f_ativo_prazo",
  "financeiro.f_ativo_entrada", "financeiro.f_ativo_valor",
  // Customizadas
  "customizada.vc_financeira_nome", "customizada.vc_nome",
  "customizada.vc_parcela_1", "customizada.vc_taxa_1",
  "customizada.vc_prazo_1", "customizada.vc_entrada_1",
  "customizada.vc_a_vista",
  // Conta energia
  "conta_energia.co2_evitado_ano", "conta_energia.gasto_atual_mensal",
  "conta_energia.economia_percentual",
]);

// ── Backend flatten: keys set via setIfMissing() in flattenSnapshot.ts ──
export const BACKEND_FLATTEN_KEYS = new Set<string>([
  // Tecnico
  "consumo_mensal", "geracao_mensal", "potencia_kwp", "potencia_sistema",
  "numero_modulos",
  // Financeiro
  "economia_mensal", "valor_total", "preco_total", "preco_final", "preco",
  "capo_i", "payback_meses", "roi_anual", "tir", "vpl",
  // Itens — módulos
  "modulo_fabricante", "modulo_modelo", "modulo_potencia",
  "vc_modulo_potencia", "modulo_quantidade", "vc_total_modulo",
  // Itens — inversores
  "inversor_fabricante", "inversor_fabricante_1", "inversor_modelo",
  "inversor_potencia_nominal", "inversores_utilizados",
  "inversor_modelo_1", "inversor_potencia_nominal_1", "inversor_quantidade_1",
  // UCs
  "subgrupo_uc1", "dis_energia", "tarifa_distribuidora", "qtd_ucs",
  // Cliente
  "cliente_nome", "vc_nome", "vc_financeira_nome",
  "cliente_celular", "cliente_email", "cliente_cnpj_cpf",
  "cliente_empresa", "cliente_cep", "cliente_endereco",
  "cliente_numero", "cliente_complemento", "cliente_bairro",
  "cliente_cidade", "cliente_estado", "cidade_estado",
  // Pagamento
  "vc_parcela_1", "f_parcela_1", "f_nome_1", "f_prazo_1",
  "f_taxa_1", "f_entrada_1", "f_valor_1",
  // Consultor
  "consultor_nome", "responsavel_nome", "consultor_telefone", "consultor_email",
]);

// ── Backend template-preview: uses flattenSnapshot output + direct substitution ──
// The template-preview function uses ALL keys from flattenSnapshot + any key
// that exists in the DOCX template. So effectively it supports all flatten keys.
export const BACKEND_TEMPLATE_PREVIEW_KEYS = new Set<string>([
  ...BACKEND_FLATTEN_KEYS,
]);

/**
 * Maps canonical dotted keys to their data source path in the snapshot/context.
 * Used to determine `canonical_source` and `source_path` for each variable.
 */
export const SOURCE_MAP: Record<string, { source: string; path: string }> = {
  // Cliente
  "cliente.nome": { source: "cliente", path: "cliente.nome" },
  "cliente.empresa": { source: "cliente", path: "cliente.empresa" },
  "cliente.cnpj_cpf": { source: "cliente", path: "cliente.cpf_cnpj" },
  "cliente.email": { source: "cliente", path: "cliente.email" },
  "cliente.celular": { source: "cliente", path: "cliente.telefone" },
  "cliente.endereco": { source: "cliente", path: "cliente.rua + numero + complemento + bairro + cidade + estado" },
  "cliente.cidade": { source: "cliente", path: "cliente.cidade" },
  "cliente.estado": { source: "cliente", path: "cliente.estado" },
  "cliente.bairro": { source: "cliente", path: "cliente.bairro" },
  "cliente.cep": { source: "cliente", path: "cliente.cep" },
  // Sistema Solar
  "sistema_solar.potencia_sistema": { source: "kit/tecnico", path: "tecnico.potencia_kwp / ctx.potenciaKwp" },
  "sistema_solar.geracao_mensal": { source: "tecnico", path: "tecnico.geracao_estimada_kwh / ctx.geracaoMensal" },
  "sistema_solar.numero_modulos": { source: "tecnico/kit", path: "tecnico.numero_modulos / ctx.numeroPlacas" },
  "sistema_solar.modulo_fabricante": { source: "itens", path: "itens[categoria=modulo].fabricante" },
  "sistema_solar.modulo_modelo": { source: "itens", path: "itens[categoria=modulo].modelo" },
  "sistema_solar.modulo_potencia": { source: "itens", path: "itens[categoria=modulo].potencia_w" },
  "sistema_solar.modulo_quantidade": { source: "itens", path: "itens[categoria=modulo].quantidade" },
  "sistema_solar.inversor_fabricante": { source: "itens", path: "itens[categoria=inversor].fabricante" },
  "sistema_solar.inversor_modelo": { source: "itens", path: "itens[categoria=inversor].modelo" },
  "sistema_solar.inversor_potencia_nominal": { source: "itens", path: "itens[categoria=inversor].potencia_w" },
  // Financeiro
  "financeiro.preco_total": { source: "financeiro/ctx", path: "financeiro.valor_total / ctx.precoTotal" },
  "financeiro.preco": { source: "financeiro/ctx", path: "financeiro.valor_total / ctx.precoTotal" },
  "financeiro.economia_mensal": { source: "financeiro/ctx", path: "financeiro.economia_mensal / ctx.economiaMensal" },
  "financeiro.economia_anual": { source: "ctx", path: "ctx.economiaAnual" },
  "financeiro.payback_anos": { source: "financeiro/ctx", path: "financeiro.payback_meses/12 / ctx.paybackAnos" },
  "financeiro.payback_meses": { source: "financeiro", path: "financeiro.payback_meses" },
  // Entrada
  "entrada.consumo_mensal": { source: "ucs", path: "ucs[0].consumo_mensal" },
  "entrada.dis_energia": { source: "ucs", path: "ucs[0].distribuidora / ucs[0].concessionaria" },
  "entrada.tarifa_distribuidora": { source: "ucs", path: "ucs[0].tarifa_kwh / ucs[0].tarifa" },
  // Tarifa
  "tarifa.te_kwh": { source: "tariffVersion", path: "tariffVersion.te_kwh" },
  "tarifa.tusd_total_kwh": { source: "tariffVersion", path: "tariffVersion.tusd_total_kwh" },
  // GD
  "gd.regra": { source: "gdResult", path: "gdResult.regra_aplicada" },
  // Customizadas
  "customizada.vc_nome": { source: "cliente", path: "cliente.nome (alias legado)" },
  "customizada.vc_financeira_nome": { source: "pagamentoOpcoes", path: "pagamentoOpcoes[tipo=financ].nome" },
  // Comercial
  "comercial.responsavel_nome": { source: "comercial/consultor", path: "comercial.responsavel_nome / consultor.nome" },
  "comercial.empresa_nome": { source: "comercial", path: "comercial.empresa_nome / ctx.empresaNome" },
};
