/**
 * Static icon map — SSOT for integration logo filenames.
 * Eliminates HTTP 404 fallback chains by mapping provider ID → exact filename.
 * Generated from public/integrations/ directory listing.
 */
const ICON_MAP: Record<string, string> = {
  // PNG assets
  abb_fimer: "abb_fimer.png",
  apsystems: "apsystems.png",
  byd: "byd.png",
  canadian_solar: "canadian_solar.png",
  csi_cloud: "csi_cloud.png",
  csi_cloudpro: "csi_cloudpro.png",
  csi_smart_energy: "csi_smart_energy.png",
  deye_cloud: "deye_cloud.png",
  enphase: "enphase.png",
  fimer: "fimer.png",
  fox_ess: "fox_ess.png",
  foxess: "foxess.png",
  goodwe: "goodwe.png",
  growatt: "growatt.png",
  growatt_server: "growatt_server.png",
  hoymiles: "hoymiles.png",
  hoymiles_s_miles: "hoymiles_s_miles.png",
  huawei: "huawei.png",
  intelbras: "intelbras.png",
  intelbras_plus: "intelbras_plus.png",
  livoltek: "livoltek.png",
  renovigi: "renovigi.png",
  saj: "saj.png",
  shinemonitor: "shinemonitor.png",
  sma: "sma.png",
  sofar: "sofar.png",
  solaredge: "solaredge.png",
  solarman_business: "solarman_business.png",
  solarman_smart: "solarman_smart.png",
  solax: "solax.png",
  solis_cloud: "solis_cloud.png",
  sungrow: "sungrow.png",
  sunny_portal: "sunny_portal.png",

  // SVG assets
  afore: "afore.svg",
  agendor: "agendor.svg",
  asaas: "asaas.svg",
  auxsol: "auxsol.svg",
  bedin_solar: "bedin_solar.svg",
  chint: "chint.svg",
  chint_flexom: "chint_flexom.svg",
  conta_azul: "conta_azul.svg",
  cora: "cora.svg",
  dah_solar: "dah_solar.svg",
  delta: "delta.svg",
  dessmonitor: "dessmonitor.svg",
  devex_erp360: "devex_erp360.svg",
  ecosolys: "ecosolys.svg",
  elekeeper: "elekeeper.svg",
  elgin: "elgin.svg",
  elsys: "elsys.svg",
  empalux: "empalux.svg",
  fronius: "fronius.svg",
  ge_solar: "ge_solar.svg",
  google_calendar: "google_calendar.svg",
  google_drive: "google_drive.svg",
  google_meet: "google_meet.svg",
  hopewind: "hopewind.svg",
  hopewind_shine: "hopewind_shine.svg",
  hubspot: "hubspot.svg",
  hypon_cloud: "hypon_cloud.svg",
  hypon_portal: "hypon_portal.svg",
  imap_smtp: "imap_smtp.svg",
  ingeteam: "ingeteam.svg",
  instagram_api: "instagram_api.svg",
  intelbras_send: "intelbras_send.svg",
  intelbras_x: "intelbras_x.svg",
  inter_bank: "inter_bank.svg",
  ja_solar: "ja_solar.svg",
  jinko_solar: "jinko_solar.svg",
  kehua: "kehua.svg",
  ksolare: "ksolare.svg",
  kstar: "kstar.svg",
  leveros: "leveros.svg",
  litto: "litto.svg",
  livoltek_cf: "livoltek_cf.svg",
  longi: "longi.svg",
  meta_facebook: "meta_facebook.svg",
  moskit: "moskit.svg",
  moso: "moso.svg",
  must_solar: "must_solar.svg",
  n8n_automation: "n8n_automation.svg",
  nansen: "nansen.svg",
  nep_viewer: "nep_viewer.svg",
  nf_emission: "nf_emission.svg",
  omie: "omie.svg",
  outlook: "outlook.svg",
  pagarme: "pagarme.svg",
  phb_solar: "phb_solar.svg",
  phono_solar: "phono_solar.svg",
  pipedrive: "pipedrive.svg",
  pix_api: "pix_api.svg",
  ploomes: "ploomes.svg",
  public_api: "public_api.svg",
  pv123: "pv123.svg",
  pvhub: "pvhub.svg",
  qcells: "qcells.svg",
  rd_station: "rd_station.svg",
  rd_station_marketing: "rd_station_marketing.svg",
  refusol: "refusol.svg",
  renac: "renac.svg",
  renovigi_portal: "renovigi_portal.svg",
  risen: "risen.svg",
  sacolar: "sacolar.svg",
  salesforce: "salesforce.svg",
  santander: "santander.svg",
  sices: "sices.svg",
  sicoob: "sicoob.svg",
  siger: "siger.svg",
  smartess: "smartess.svg",
  smten: "smten.svg",
  solar_must: "solar_must.svg",
  solarnex: "solarnex.svg",
  solarview: "solarview.svg",
  solplanet: "solplanet.svg",
  sunwave: "sunwave.svg",
  sunweg: "sunweg.svg",
  trina_solar: "trina_solar.svg",
  tsun: "tsun.svg",
  tsun_pro: "tsun_pro.svg",
  victron: "victron.svg",
  wdc_solar: "wdc_solar.svg",
  wdc_solar_cf: "wdc_solar_cf.svg",
  webhooks_generic: "webhooks_generic.svg",
  weg_iot: "weg_iot.svg",
  whatsapp_evolution: "whatsapp_evolution.svg",
  zapier: "zapier.svg",
  zapsign: "zapsign.svg",
  zevercloud: "zevercloud.svg",
};

/**
 * Resolve provider ID to icon URL. Returns null if no icon exists.
 * Uses static map — zero HTTP fallback, instant resolution.
 */
export function getProviderIconUrl(providerId: string): string | null {
  const file = ICON_MAP[providerId];
  if (file) return `/integrations/${file}`;

  // Try base ID (e.g. goodwe_sems → goodwe)
  const base = providerId.split("_")[0];
  if (base !== providerId) {
    const baseFile = ICON_MAP[base];
    if (baseFile) return `/integrations/${baseFile}`;
  }

  return null;
}
