
export const ALLOWED_ADMIN_ROLES = ["admin", "gerente", "financeiro"];

export const TAB_TITLES: Record<string, string> = {
  "meu-painel": "Meu Painel",
  dashboard: "Painel geral",
  inteligencia: "Inteligência comercial",
  diretor: "Assistente IA",
  auditoria: "Registro de atividades",
  leads: "Leads",
  pipeline: "Funil comercial",
  distribuicao: "Distribuição de leads",
  "sla-breaches": "Alertas de prazo",
  "motivos-perda": "Motivos de perda",
  "origens-lead": "Origens de lead",
  inbox: "Atendimento",
  "respostas-rapidas": "Respostas rápidas",
  followup: "Acompanhamentos",
  "followup-comercial": "Recuperação Comercial",
  preventiva: "Central Preventiva",
  validacao: "Aprovação de vendas",
  tarefas: "Tarefas & prazos",
  clientes: "Clientes",
  checklists: "Documentação",
  avaliacoes: "Satisfação (NPS)",
  instaladores: "Equipe técnica",
  servicos: "Agenda de serviços",
  "visitas-tecnicas": "Visitas técnicas",
  "financeiro-dashboard": "Financeiro",
  lancamentos: "Lançamentos Financeiros",
  dre: "DRE",
  recebimentos: "Contas a receber",
  inadimplencia: "Inadimplência",
  comissoes: "Comissões",
  engenharia: "Premissas", 
  financiamento: "Financiamentos",
  "site-config": "Conteúdo & visual",
  brand: "Conteúdo & visual",
  "site-servicos": "Serviços do site",
  obras: "Portfólio",
  aprovacao: "Solicitações de acesso",
  vendedores: "Consultores",
  usuarios: "Usuários & permissões",
  gamificacao: "Metas & ranking",
  "lead-status": "Etapas do funil",
  equipamentos: "Disjuntores & transf.",
  modulos: "Módulos fotovoltaicos",
  "inversores-cadastro": "Inversores",
  baterias: "Baterias",
  concessionarias: "Concessionárias",
  config: "Calculadora solar",
  whatsapp: "WhatsApp API",
  instagram: "Instagram",
  webhooks: "Webhooks",
  n8n: "Automações",
  automacoes: "Central de Automações",
  "wa-instances": "Instâncias WhatsApp",
  release: "Checklist de versão",
  propostas: "Propostas comerciais",
  projetos: "Projetos",
  "propostas/novo": "Nova proposta",
  "propostas-nativas/nova": "Nova proposta",
  "propostas-nativas/templates": "Templates de proposta",
  "propostas-nativas/variaveis": "Variáveis customizadas",
  "followup-wa": "Regras de retorno",
  "regras-retorno": "Regras de retorno",
  "followup-queue": "Fila de retorno",
  "followup-wa-queue": "Fila de retorno",
  "metricas-atendimento": "Métricas de atendimento",
  "wa-etiquetas": "Etiquetas WhatsApp",
  "links-instalacao": "Captação & app",
  documentos: "Documentos & assinatura",
  "documentos-assinaturas": "Documentos & assinatura",
  "data-reset": "Manutenção de dados",
  "backup": "Backup de Dados",
  "integracoes": "Integrações",
  "aneel": "Integração ANEEL",
  "pos-venda": "Dashboard pós-venda",
  "pos-venda-visitas": "Preventivas",
  "pos-venda-planos": "Planos pós-venda",
  "pos-venda-upsell": "Oportunidades",
  "pos-venda-checklists": "Checklists pós-venda",
  integridade: "Integridade do Sistema",
  "payment-gateway": "Pagamentos (Asaas)",
  "meu-plano": "Meu Plano & Uso",
  "ai-config": "Configuração de IA",
  "proposta-comercial": "Proposta Comercial",
  changelog: "Atualizações do sistema",
  "notificacoes-config": "Notificações",
  "loading-config": "Personalização visual",
  "tenant-settings": "Empresa",
  "monitoramento-solar": "Monitoramento Solar",
  "conf-solar": "Premissas solar",
  "variaveis-sistema": "Variáveis do Sistema",
  "pricing-policy": "Política de precificação",
  "politica-precos": "Política de precificação",
  "custom-fields": "Campos customizados",
  menus: "Personalizar menu",
  dev: "Ferramentas dev",
  "cron-jobs": "Tarefas Agendadas",
  "dicionario-aneel": "Dicionário ANEEL",
  "tarifa-versoes": "Versões de tarifa",
  "saude-tarifaria": "Saúde tarifária",
  "aneel-sync-status": "Status do Sync ANEEL",
  medidores: "Medidores",
  ucs: "Unidades Consumidoras",
  "faturas-energia": "Faturas de Energia",
  "central-extracao": "Central de Extração",
  "alertas-energia": "Alertas Energéticos",
};
