
INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('inteligencia', 'inteligencia-visao-geral', 'Visão Geral da Inteligência Comercial', 'Entenda como a IA analisa seus leads automaticamente', E'## 🧠 Inteligência Comercial\n\nA Inteligência Comercial usa **IA** para analisar automaticamente seus leads e fornecer insights acionáveis.\n\n### O que a IA analisa:\n\n- **Temperamento** — Quente, Morno, Frio ou Congelado\n- **Urgência** — Score de 0 a 100\n- **Dor principal** — O que mais motiva o lead\n- **Objeções** — Barreiras identificadas na conversa\n- **Sugestões** — Abordagens recomendadas\n\n### Como ativar:\n\n1. Acesse **Admin > Inteligência Comercial**\n2. Na aba **Geral**, ative o módulo\n3. Configure os thresholds de urgência\n4. Pronto! A IA começa a analisar automaticamente\n\n### Dica:\nQuanto mais conversas no WhatsApp, mais precisa será a análise!', 1, 'Brain', ARRAY['inteligencia','ia','leads','temperamento'], true);

INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('inteligencia', 'inteligencia-perfis', 'Perfis de Inteligência dos Leads', 'Como interpretar os perfis gerados pela IA', E'## 📊 Perfis de Inteligência\n\nCada lead recebe um **perfil de inteligência** atualizado automaticamente.\n\n### Campos do perfil:\n\n- **Temperamento**: Classificação geral do interesse\n  - 🔥 Quente — Pronto para comprar\n  - 🌡️ Morno — Interessado, precisa de empurrão\n  - ❄️ Frio — Pouco interesse demonstrado\n  - 🧊 Congelado — Inativo há muito tempo\n\n- **Urgência Score (0-100)**: Quanto maior, mais urgente agir\n- **Dor Principal**: Motivação detectada\n- **Objeções**: Barreiras identificadas\n\n### Como usar:\n\n1. Abra o perfil do lead no pipeline\n2. Veja a aba **Inteligência**\n3. Use as sugestões de abordagem\n4. Priorize leads quentes e com alta urgência', 2, 'BarChart3', ARRAY['inteligencia','perfis','temperamento','urgencia'], false);

INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('inteligencia', 'inteligencia-reaquecimento', 'Reaquecimento de Leads Congelados', 'Recupere leads inativos com estratégias automáticas', E'## 🔄 Reaquecimento de Leads\n\nLeads inativos representam **valor perdido**. O módulo de reaquecimento identifica oportunidades.\n\n### Como funciona:\n\n1. Sistema identifica leads sem interação há 30+ dias\n2. IA calcula o valor perdido\n3. Gera oportunidades de reaquecimento priorizadas\n4. Sugere mensagens personalizadas\n\n### Variáveis para mensagens:\n- `{{nome}}` — Nome do lead\n- `{{valor_perdido}}` — Valor que deixou de economizar\n- `{{potencia}}` — Potência do projeto em kWp\n- `{{data_primeiro_contato}}` — Data do primeiro contato', 3, 'RefreshCw', ARRAY['reaquecimento','cron','leads-inativos'], false);

INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('inteligencia', 'inteligencia-whatsapp', 'WhatsApp em Tempo Real', 'Receba alertas quando leads mudarem de temperamento durante conversas', E'## 💬 WhatsApp em Tempo Real\n\nAnálise de sentimento **durante** a conversa, não depois.\n\n### O que faz:\n\nQuando cliente manda mensagem:\n1. IA analisa em segundos\n2. Detecta mudança de temperamento\n3. Mostra banner no topo do chat\n4. Sugere resposta pronta\n\n### Cores do temperamento:\n- 🔥 **Quente** — Urgência 80-100\n- 🌡️ **Morno** — Urgência 50-79\n- ❄️ **Frio** — Urgência < 50\n- 🧊 **Congelado** — Inativo 180+ dias\n\n### Dica:\nMantenha o chat aberto. Quanto mais rápido responder após alerta, maior a chance de conversão!', 4, 'MessageSquare', ARRAY['whatsapp','tempo-real','alertas'], false);

INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('comercial', 'pipeline-kanban', 'Pipeline Kanban', 'Como usar o pipeline visual para gerenciar leads', E'## 📊 Pipeline Kanban\n\nVisualize e mova leads entre etapas do funil.\n\n### Colunas padrão:\n- **Novo** — Lead recém cadastrado\n- **Em Contato** — Primeira tentativa de contato\n- **Aguardando** — Proposta enviada\n- **Negociação** — Discutindo valores\n- **Fechamento** — Quase convertendo\n- **Convertido** — Venda realizada 🎉\n\n### Ações:\n- **Arrastar** — Mover lead entre colunas\n- **Clique** — Abrir detalhes do lead\n\n### Filtros:\n- Por consultor\n- Por origem\n- Por urgência\n\n### Atalhos:\n- `N` — Novo lead\n- `F` — Filtros\n- `E` — Exportar', 1, 'Kanban', ARRAY['pipeline','kanban','leads'], false);

INSERT INTO public.help_center_tutorials (categoria, slug, titulo, descricao_curta, conteudo, ordem, icon, tags, is_destaque) VALUES
('whatsapp', 'whatsapp-massa', 'Disparo em Massa', 'Como enviar mensagens para múltiplos leads', E'## 📤 Disparo em Massa\n\nEnvie mensagens personalizadas para lista de leads.\n\n### Passo a passo:\n\n1. **Selecionar leads** — Pipeline > Selecionar múltiplos ou importar CSV\n2. **Criar mensagem** — Use variáveis: `{{nome}}`, `{{cidade}}`, `{{potencia}}`\n3. **Agendar ou enviar** — Imediato ou agendar data/hora\n4. **Acompanhar** — Relatório de entregas\n\n### Dicas:\n- Não envie mais que 100/hora\n- Use horários comerciais (9h-18h)\n- Mensagens personalizadas têm 3x mais respostas\n\n### Variáveis disponíveis:\n- `{{nome}}`, `{{telefone}}`, `{{email}}`\n- `{{cidade}}`, `{{estado}}`\n- `{{consumo}}`, `{{potencia}}`, `{{valor_projeto}}`', 1, 'Send', ARRAY['whatsapp','disparo','massa'], false);
