
-- Seed integration_providers catalog
INSERT INTO public.integration_providers (id, category, label, description, logo_key, status, auth_type, credential_schema, tutorial, capabilities, platform_managed_keys, popularity) VALUES
-- Monitoramento Solar
('solarman_business', 'monitoring', 'Solarman Business', 'Monitoramento de usinas via Solarman Business API', 'Sun', 'available', 'platform_app_user_login', '[{"key":"appId","label":"App ID","type":"text","required":true,"placeholder":"Ex: 201911067156002"},{"key":"appSecret","label":"App Secret","type":"password","required":true,"placeholder":"Seu App Secret"},{"key":"email","label":"E-mail Solarman","type":"email","required":true,"placeholder":"seu@email.com"},{"key":"password","label":"Senha","type":"password","required":true,"placeholder":"Senha do Solarman"}]'::jsonb, '{"steps":["Acesse o portal Solarman Pro/Developer","Gere o App (App ID / App Secret)","Preencha App ID, App Secret, Email e Senha","A senha é usada só para autenticar — NÃO armazenamos senha","Obs: a senha é enviada como SHA-256"],"notes":"Você precisa de App ID e App Secret (modo Developer/OpenAPI)."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 95),
('solaredge', 'monitoring', 'SolarEdge', 'Monitoramento de inversores SolarEdge via API Key', 'Zap', 'available', 'api_key', '[{"key":"apiKey","label":"API Key","type":"text","required":true,"placeholder":"Sua API Key do SolarEdge"}]'::jsonb, '{"steps":["Acesse monitoring.solaredge.com e faça login","Clique no seu nome → Minha Conta → Dados da Empresa","No painel Acesso à API, marque que concorda com os termos (API T&C) e salve","Copie a API KEY","Sites serão detectados automaticamente"],"notes":"Se não aparecer Acesso à API, sua conta pode não ser Administrador."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 90),
('solis_cloud', 'monitoring', 'Solis Cloud', 'Monitoramento via SolisCloud Platform API V2.0', 'CloudSun', 'available', 'api_key', '[{"key":"apiId","label":"API ID (KeyID)","type":"text","required":true,"placeholder":"Seu API ID"},{"key":"apiSecret","label":"API Secret (KeySecret)","type":"password","required":true,"placeholder":"Seu API Secret"}]'::jsonb, '{"steps":["Faça login no SolisCloud","Vá em Configurações básicas (Basic Settings)","Procure Gerenciamento de API / API Management","Ative e copie o API ID (KeyID) e API Secret (KeySecret)"],"notes":"Se NÃO aparecer API Management, solicite habilitação ao Solis. A conta precisa ser de Instalador ou Proprietário."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 85),
('growatt', 'monitoring', 'Growatt ShineServer', 'Monitoramento de inversores Growatt', 'Sprout', 'coming_soon', 'api_key', '[{"key":"apiToken","label":"API Token","type":"text","required":true,"placeholder":"Seu token da API Growatt"}]'::jsonb, '{"steps":["Acesse o portal Growatt","Vá em Settings → Account Management → API Key","Gere e copie o token"],"notes":"Em breve."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 80),
('huawei_fusionsolar', 'monitoring', 'Huawei FusionSolar', 'Monitoramento via FusionSolar OpenAPI', 'Cpu', 'coming_soon', 'api_key', '[{"key":"username","label":"Usuário","type":"text","required":true},{"key":"password","label":"Senha","type":"password","required":true},{"key":"systemCode","label":"System Code","type":"text","required":true}]'::jsonb, '{"steps":["Prepare usuário, senha e dados do portal FusionSolar","O acesso pode exigir habilitação via OpenAPI/OAuth"],"notes":"Em breve."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 75),
('goodwe_sems', 'monitoring', 'GoodWe SEMS', 'Monitoramento via SEMS Portal', 'Gauge', 'coming_soon', 'portal', '[{"key":"email","label":"E-mail","type":"email","required":true},{"key":"password","label":"Senha","type":"password","required":true}]'::jsonb, '{"steps":["Prepare usuário e senha do SEMS"],"notes":"Em breve."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 70),
('sungrow_isolarcloud', 'monitoring', 'Sungrow iSolarCloud', 'Monitoramento via iSolarCloud', 'SunDim', 'coming_soon', 'api_key', '[{"key":"email","label":"E-mail","type":"email","required":true},{"key":"password","label":"Senha","type":"password","required":true}]'::jsonb, '{"steps":["Requer App Key/Access Key via portal de desenvolvedor"],"notes":"Em breve."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 65),
('hoymiles_s_miles', 'monitoring', 'Hoymiles S-Miles', 'Monitoramento de microinversores Hoymiles', 'Radio', 'coming_soon', 'api_key', '[{"key":"login","label":"Usuário","type":"text","required":true},{"key":"password","label":"Senha","type":"password","required":true}]'::jsonb, '{"steps":["Prepare dados do S-Miles Cloud"],"notes":"API pode não ser pública para clientes finais."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 60),
('deye_cloud', 'monitoring', 'Deye Cloud', 'Monitoramento de inversores Deye', 'Sun', 'coming_soon', 'api_key', '[{"key":"appId","label":"App ID","type":"text","required":true},{"key":"appSecret","label":"App Secret","type":"password","required":true}]'::jsonb, '{"steps":["Acesse o portal de desenvolvedor Deye","Solicite App ID e App Secret"],"notes":"Em breve."}'::jsonb, '{"sync_plants":true,"sync_metrics":true}'::jsonb, false, 55),
-- CRM
('hubspot', 'crm', 'HubSpot', 'CRM e automação de marketing', 'Users', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via OAuth do HubSpot"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true,"sync_contacts":true}'::jsonb, false, 80),
('pipedrive', 'crm', 'Pipedrive', 'CRM focado em vendas', 'Users', 'coming_soon', 'api_key', '[{"key":"apiToken","label":"API Token","type":"text","required":true}]'::jsonb, '{"steps":["Configurações → Pessoal → API","Copie seu token pessoal"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true,"sync_contacts":true}'::jsonb, false, 75),
('salesforce', 'crm', 'Salesforce', 'CRM empresarial', 'Building2', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via OAuth"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true,"sync_contacts":true}'::jsonb, false, 70),
('agendor', 'crm', 'Agendor', 'CRM brasileiro para vendas', 'Users', 'coming_soon', 'api_key', '[{"key":"apiToken","label":"Token API","type":"text","required":true}]'::jsonb, '{"steps":["Configurações → Integrações → API"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true,"sync_contacts":true}'::jsonb, false, 60),
('moskit', 'crm', 'Moskit CRM', 'CRM focado no mercado brasileiro', 'Users', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Acesse configurações do Moskit"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true}'::jsonb, false, 55),
('ploomes', 'crm', 'Ploomes', 'CRM para operações complexas', 'Users', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Acesse configurações do Ploomes"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true}'::jsonb, false, 50),
('rd_station', 'crm', 'RD Station CRM', 'CRM da RD Station', 'Users', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via OAuth"],"notes":"Em breve."}'::jsonb, '{"sync_deals":true,"sync_contacts":true}'::jsonb, false, 65),
('rd_station_marketing', 'crm', 'RD Station Marketing', 'Automação de marketing', 'Mail', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via OAuth"],"notes":"Em breve."}'::jsonb, '{"sync_contacts":true}'::jsonb, false, 60),
-- Armazenamento
('google_drive', 'storage', 'Google Drive', 'Armazenamento de documentos', 'HardDrive', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via conta Google"],"notes":"Em breve."}'::jsonb, '{"upload_files":true,"sync_folders":true}'::jsonb, false, 80),
-- Calendário
('google_calendar', 'calendar', 'Google Agenda', 'Sincronização de agenda', 'Calendar', 'available', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via conta Google","Autorizar acesso à agenda"],"notes":"Configurado no sistema."}'::jsonb, '{"sync_events":true,"create_events":true}'::jsonb, false, 90),
-- E-mail
('imap_smtp', 'email', 'IMAP / SMTP', 'Integração com e-mail via IMAP', 'Mail', 'coming_soon', 'imap_password', '[{"key":"host","label":"Servidor IMAP","type":"text","required":true},{"key":"port","label":"Porta","type":"text","required":true},{"key":"email","label":"E-mail","type":"email","required":true},{"key":"password","label":"Senha de app","type":"password","required":true}]'::jsonb, '{"steps":["Configure uma senha de aplicativo","Preencha servidor, porta, e-mail e senha"],"notes":"Em breve."}'::jsonb, '{"read_emails":true,"send_emails":true}'::jsonb, false, 60),
('outlook', 'email', 'Microsoft Outlook', 'Integração com Outlook/Exchange', 'Mail', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via conta Microsoft"],"notes":"Em breve."}'::jsonb, '{"read_emails":true,"send_emails":true}'::jsonb, false, 55),
-- Mensagens
('whatsapp_evolution', 'messaging', 'WhatsApp (Evolution API)', 'Envio e recebimento via WhatsApp', 'MessageCircle', 'available', 'api_key', '[]'::jsonb, '{"steps":["Configurado via Instâncias WhatsApp"],"notes":"Gerenciado na seção Instâncias WhatsApp."}'::jsonb, '{"send_message":true,"receive_message":true}'::jsonb, false, 99),
('instagram_api', 'messaging', 'Instagram', 'Integração com Instagram', 'Instagram', 'available', 'api_key', '[]'::jsonb, '{"steps":["Configurado via Meta/Facebook"],"notes":"Gerenciado na seção Instagram."}'::jsonb, '{"sync_posts":true}'::jsonb, false, 70),
('meta_facebook', 'messaging', 'Meta (Facebook Ads)', 'Captura de leads e métricas', 'Facebook', 'available', 'api_key', '[]'::jsonb, '{"steps":["Configurado via seção Meta"],"notes":"Gerenciado na seção Meta."}'::jsonb, '{"capture_leads":true,"sync_campaigns":true}'::jsonb, false, 85),
-- Reuniões
('google_meet', 'meetings', 'Google Meet', 'Videoconferências', 'Video', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via conta Google"],"notes":"Em breve."}'::jsonb, '{"create_meeting":true}'::jsonb, false, 65),
-- Cobranças / Financeiro
('asaas', 'billing', 'Asaas', 'Cobranças via boleto, Pix e cartão', 'CreditCard', 'available', 'api_key', '[{"key":"apiKey","label":"API Key","type":"text","required":true}]'::jsonb, '{"steps":["Asaas → Configurações → Integrações","Copie sua chave de API"],"notes":"Configurado no sistema."}'::jsonb, '{"create_charge":true,"list_payments":true}'::jsonb, false, 90),
('pagarme', 'billing', 'Pagar.me', 'Gateway de pagamento', 'CreditCard', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Pagar.me Dashboard"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 60),
('cora', 'billing', 'Cora', 'Conta digital e cobranças', 'Building2', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Solicite acesso à API Cora"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 50),
('sicoob', 'billing', 'Sicoob', 'Cobranças via Sicoob', 'Building2', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Solicite acesso à API"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 45),
('inter_bank', 'billing', 'Banco Inter', 'Cobranças e Pix via Inter', 'Building2', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Internet Banking → API"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 55),
('santander', 'billing', 'Santander', 'Cobranças e boletos', 'Building2', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Solicite acesso à API"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 50),
('pix_api', 'billing', 'PIX (Genérico)', 'Integração PIX via PSP', 'QrCode', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Configure via seu PSP"],"notes":"Em breve."}'::jsonb, '{"create_charge":true}'::jsonb, false, 70),
('omie', 'billing', 'Omie ERP', 'ERP e gestão financeira', 'Calculator', 'coming_soon', 'api_key', '[{"key":"appKey","label":"App Key","type":"text","required":true},{"key":"appSecret","label":"App Secret","type":"password","required":true}]'::jsonb, '{"steps":["Omie → Configurações → API","Copie App Key e App Secret"],"notes":"Em breve."}'::jsonb, '{"sync_invoices":true,"sync_clients":true}'::jsonb, false, 65),
('conta_azul', 'billing', 'Conta Azul', 'ERP contábil e financeiro', 'Calculator', 'coming_soon', 'oauth2', '[]'::jsonb, '{"steps":["Conectar via OAuth"],"notes":"Em breve."}'::jsonb, '{"sync_invoices":true}'::jsonb, false, 60),
('siger', 'billing', 'Siger ERP', 'ERP para energia solar', 'Calculator', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Solicite acesso à API"],"notes":"Em breve."}'::jsonb, '{"sync_projects":true}'::jsonb, false, 40),
('devex_erp360', 'billing', 'DEVEX ERP 360', 'ERP integrado para solar', 'Calculator', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Solicite acesso à API"],"notes":"Em breve."}'::jsonb, '{"sync_projects":true}'::jsonb, false, 35),
('nf_emission', 'nf', 'Emissão de NF', 'Emissão de notas fiscais de serviço', 'ReceiptText', 'available', 'api_key', '[]'::jsonb, '{"steps":["Configurado via módulo Fiscal"],"notes":"Gerenciado na seção Fiscal."}'::jsonb, '{"emit_nf":true}'::jsonb, false, 80),
-- API
('webhooks_generic', 'api', 'Webhooks', 'Receba e envie eventos via webhooks', 'Webhook', 'available', 'webhook_only', '[]'::jsonb, '{"steps":["Configure URLs no painel"],"notes":"Configurado."}'::jsonb, '{"send_webhook":true,"receive_webhook":true}'::jsonb, false, 85),
('public_api', 'api', 'API Pública', 'API REST para integração externa', 'Globe', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Gere uma chave no painel"],"notes":"Em breve."}'::jsonb, '{"rest_api":true}'::jsonb, false, 70),
-- Automação
('zapier', 'automation', 'Zapier', 'Automatize tarefas entre apps', 'Workflow', 'coming_soon', 'api_key', '[]'::jsonb, '{"steps":["Conecte sua conta Zapier"],"notes":"Em breve."}'::jsonb, '{"trigger":true,"action":true}'::jsonb, false, 75),
('n8n_automation', 'automation', 'n8n / Automações', 'Workflows avançados', 'Workflow', 'available', 'webhook_only', '[]'::jsonb, '{"steps":["Configure via webhooks"],"notes":"Configurado."}'::jsonb, '{"trigger":true,"action":true}'::jsonb, false, 70),
-- Assinatura Digital
('zapsign', 'signature', 'ZapSign', 'Assinatura digital de documentos', 'FileSignature', 'coming_soon', 'api_key', '[{"key":"apiToken","label":"Token API","type":"text","required":true}]'::jsonb, '{"steps":["ZapSign → Configurações → API","Copie seu token"],"notes":"Em breve."}'::jsonb, '{"create_document":true,"sign_document":true}'::jsonb, false, 65)
ON CONFLICT (id) DO NOTHING;
