// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihamnhskrmbbvowtyxme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloYW1uaHNrcm1iYnZvd3R5eG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0Mjk1ODAsImV4cCI6MjA4NjAwNTU4MH0.bw_wIMxMJqk6tPeWB5RbmYJYU0sTOMX2KGDmwbGv9qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});